-- Remove vendors that do not have a public-facing certification program.
-- Tables/columns: lowercase snake_case (vendors, certifications, notifications, user_certifications).
-- Delete order respects FKs (no cascade): notifications → user_certifications → certifications → vendors.
--
-- Before running: consider a dry run (SELECT/COUNT with same WHEREs) and a DB backup or Neon branch.
-- To preview without committing: run with COMMIT replaced by ROLLBACK at the end.

BEGIN;

-- Temp tables so all DELETEs can reference the same IDs (CTEs only apply to the next statement).
CREATE TEMP TABLE target_vendors (id text PRIMARY KEY);
INSERT INTO target_vendors
SELECT id FROM vendors WHERE name IN (
    '1Password Business',
    '42Crunch',
    '8x8',
    'A10 Networks',
    'Abnormal Security',
    'Absorb LMS',
    'Acceldata',
    'Acoustic Campaign',
    'ActiveCampaign',
    'Ada',
    'ADP Workforce Now',
    'ADT',
    'Aha!',
    'Airbyte',
    'Airtable',
    'Allied Telesis',
    'Amplitude',
    'Amundsen',
    'Anomalo',
    'Apollo.io',
    'Appcues',
    'Apple',
    'Arctic Wolf',
    'Ashby',
    'Astronomer',
    'Atlan',
    'Avanan',
    'Backblaze B2',
    'BambooHR',
    'BigCommerce',
    'BigID',
    'BigPanda',
    'Bill.com',
    'Bloomreach Engagement',
    'Box',
    'Braze',
    'Buildkite',
    'Calendly',
    'Chargebee',
    'Chorus.ai',
    'Clari',
    'CleverTap',
    'Cohesity',
    'commercetools',
    'Coupa',
    'Customer.io',
    'Darktrace',
    'DigitalOcean',
    'Docebo',
    'Domino Data Lab',
    'Domo',
    'Drata',
    'Dropbox Business',
    'Druva',
    'Eightfold AI',
    'Emarsys',
    'Exabeam',
    'Expensify',
    'Figma',
    'Five9',
    'Forethought',
    'FullStory',
    'GoodData',
    'Greenhouse',
    'Gusto',
    'Heap Analytics',
    'Hevo Data',
    'Honeycomb.io',
    'Hotjar',
    'Hugging Face Enterprise',
    'iCIMS',
    'Insider',
    'Intercom',
    'Iterable',
    'JAMF',
    'JazzHR',
    'Jitterbit',
    'JumpCloud',
    'Kandji',
    'Kentik',
    'Klaviyo',
    'Klipfolio',
    'Labelbox',
    'LearnUpon',
    'Lever',
    'LivePerson',
    'LogicGate',
    'LogicMonitor',
    'Logz.io',
    'Lucid (Lucidchart/Lucidspark)',
    'Mailchimp',
    'ManageEngine',
    'Matillion',
    'Meltano',
    'Miro',
    'Mixpanel',
    'MoEngage',
    'Monday.com',
    'Monte Carlo',
    'Moogsoft',
    'mParticle',
    'Nagios XI',
    'NetBrain',
    'NICE CXone',
    'NinjaOne',
    'Noname Security',
    'Notion',
    'OneTrust',
    'Orca Security',
    'Outreach',
    'PagerDuty',
    'PayPal / Braintree',
    'Pendo',
    'Pipedrive',
    'Portainer',
    'Postman',
    'Productboard',
    'Proofpoint',
    'Qualtrics',
    'QuickBooks Online',
    'Radware',
    'Recurly',
    'Reltio',
    'RingCentral',
    'Roadmunk',
    'Rollbar',
    'Rubrik',
    'Salt Security',
    'SeekOut',
    'Segment (Twilio)',
    'SendGrid',
    'Sentry',
    'Shopify',
    'Sigma Computing',
    'SingleStore',
    'Sisense',
    'Slack',
    'Smartsheet',
    'Snowplow Analytics',
    'Soda',
    'Squarespace Commerce',
    'Stibo Systems',
    'Stripe',
    'SurveyMonkey',
    'Tamr',
    'Tealium',
    'ThoughtSpot',
    'TimescaleDB',
    'Totango',
    'Traceable AI',
    'Tray.io',
    'TrustArc',
    'Twilio',
    'Typeform',
    'UserTesting',
    'UserZoom',
    'Vanta',
    'Varonis',
    'Versa Networks',
    'VTEX',
    'Wallarm',
    'Wasabi',
    'Weights & Biases',
    'Wix eCommerce',
    'Workable',
    'Workato',
    'Xero',
    'YugabyteDB',
    'Zabbix',
    'Zapier',
    'ZoomInfo',
    'Zuora',
    'Zyxel Networks'
);

CREATE TEMP TABLE target_cert_ids (id text PRIMARY KEY);
INSERT INTO target_cert_ids
SELECT id FROM certifications WHERE vendor_id IN (SELECT id FROM target_vendors);

-- 1. Notifications referencing those certs or user_certifications for those certs
DELETE FROM notifications
WHERE certification_id IN (SELECT id FROM target_cert_ids)
   OR user_certification_id IN (
       SELECT id FROM user_certifications WHERE certification_id IN (SELECT id FROM target_cert_ids)
   );

-- 2. User certifications for those certs
DELETE FROM user_certifications
WHERE certification_id IN (SELECT id FROM target_cert_ids);

-- 3. Certifications for those vendors
DELETE FROM certifications
WHERE vendor_id IN (SELECT id FROM target_vendors);

-- 4. Vendors
DELETE FROM vendors
WHERE id IN (SELECT id FROM target_vendors);

COMMIT;
