/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamManagementRouteImport } from './routes/team-management'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DbHealthRouteImport } from './routes/db-health'
import { Route as ComplianceAuditRouteImport } from './routes/compliance-audit'
import { Route as CertificationManagementRouteImport } from './routes/certification-management'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserProfileSplatRouteImport } from './routes/user-profile.$'
import { Route as ApiUsersRouteImport } from './routes/api.users'
import { Route as ApiTeamsRouteImport } from './routes/api.teams'
import { Route as ApiTeamRequirementsRouteImport } from './routes/api.team-requirements'
import { Route as ApiTeamMembersRouteImport } from './routes/api.team-members'
import { Route as ApiNotificationsRouteImport } from './routes/api.notifications'
import { Route as ApiNotificationSettingsRouteImport } from './routes/api.notification-settings'
import { Route as ApiExportRouteImport } from './routes/api.export'
import { Route as ApiDashboardRouteImport } from './routes/api.dashboard'
import { Route as ApiComplianceRouteImport } from './routes/api.compliance'
import { Route as ApiCertificationsRouteImport } from './routes/api.certifications'
import { Route as ApiCatalogRouteImport } from './routes/api.catalog'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const TeamManagementRoute = TeamManagementRouteImport.update({
  id: '/team-management',
  path: '/team-management',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DbHealthRoute = DbHealthRouteImport.update({
  id: '/db-health',
  path: '/db-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceAuditRoute = ComplianceAuditRouteImport.update({
  id: '/compliance-audit',
  path: '/compliance-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationManagementRoute = CertificationManagementRouteImport.update({
  id: '/certification-management',
  path: '/certification-management',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileSplatRoute = UserProfileSplatRouteImport.update({
  id: '/user-profile/$',
  path: '/user-profile/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsRoute = ApiTeamsRouteImport.update({
  id: '/api/teams',
  path: '/api/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamRequirementsRoute = ApiTeamRequirementsRouteImport.update({
  id: '/api/team-requirements',
  path: '/api/team-requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamMembersRoute = ApiTeamMembersRouteImport.update({
  id: '/api/team-members',
  path: '/api/team-members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationSettingsRoute = ApiNotificationSettingsRouteImport.update({
  id: '/api/notification-settings',
  path: '/api/notification-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplianceRoute = ApiComplianceRouteImport.update({
  id: '/api/compliance',
  path: '/api/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCertificationsRoute = ApiCertificationsRouteImport.update({
  id: '/api/certifications',
  path: '/api/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/certification-management': typeof CertificationManagementRoute
  '/compliance-audit': typeof ComplianceAuditRoute
  '/db-health': typeof DbHealthRoute
  '/health': typeof HealthRoute
  '/metrics': typeof MetricsRoute
  '/notifications': typeof NotificationsRoute
  '/ready': typeof ReadyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/team-management': typeof TeamManagementRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/certifications': typeof ApiCertificationsRoute
  '/api/compliance': typeof ApiComplianceRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/export': typeof ApiExportRoute
  '/api/notification-settings': typeof ApiNotificationSettingsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/team-members': typeof ApiTeamMembersRoute
  '/api/team-requirements': typeof ApiTeamRequirementsRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/users': typeof ApiUsersRoute
  '/user-profile/$': typeof UserProfileSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/certification-management': typeof CertificationManagementRoute
  '/compliance-audit': typeof ComplianceAuditRoute
  '/db-health': typeof DbHealthRoute
  '/health': typeof HealthRoute
  '/metrics': typeof MetricsRoute
  '/notifications': typeof NotificationsRoute
  '/ready': typeof ReadyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/team-management': typeof TeamManagementRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/certifications': typeof ApiCertificationsRoute
  '/api/compliance': typeof ApiComplianceRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/export': typeof ApiExportRoute
  '/api/notification-settings': typeof ApiNotificationSettingsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/team-members': typeof ApiTeamMembersRoute
  '/api/team-requirements': typeof ApiTeamRequirementsRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/users': typeof ApiUsersRoute
  '/user-profile/$': typeof UserProfileSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/certification-management': typeof CertificationManagementRoute
  '/compliance-audit': typeof ComplianceAuditRoute
  '/db-health': typeof DbHealthRoute
  '/health': typeof HealthRoute
  '/metrics': typeof MetricsRoute
  '/notifications': typeof NotificationsRoute
  '/ready': typeof ReadyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/team-management': typeof TeamManagementRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/certifications': typeof ApiCertificationsRoute
  '/api/compliance': typeof ApiComplianceRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/export': typeof ApiExportRoute
  '/api/notification-settings': typeof ApiNotificationSettingsRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/team-members': typeof ApiTeamMembersRoute
  '/api/team-requirements': typeof ApiTeamRequirementsRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/users': typeof ApiUsersRoute
  '/user-profile/$': typeof UserProfileSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/certification-management'
    | '/compliance-audit'
    | '/db-health'
    | '/health'
    | '/metrics'
    | '/notifications'
    | '/ready'
    | '/sign-in'
    | '/sign-up'
    | '/team-management'
    | '/api/catalog'
    | '/api/certifications'
    | '/api/compliance'
    | '/api/dashboard'
    | '/api/export'
    | '/api/notification-settings'
    | '/api/notifications'
    | '/api/team-members'
    | '/api/team-requirements'
    | '/api/teams'
    | '/api/users'
    | '/user-profile/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/certification-management'
    | '/compliance-audit'
    | '/db-health'
    | '/health'
    | '/metrics'
    | '/notifications'
    | '/ready'
    | '/sign-in'
    | '/sign-up'
    | '/team-management'
    | '/api/catalog'
    | '/api/certifications'
    | '/api/compliance'
    | '/api/dashboard'
    | '/api/export'
    | '/api/notification-settings'
    | '/api/notifications'
    | '/api/team-members'
    | '/api/team-requirements'
    | '/api/teams'
    | '/api/users'
    | '/user-profile/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/certification-management'
    | '/compliance-audit'
    | '/db-health'
    | '/health'
    | '/metrics'
    | '/notifications'
    | '/ready'
    | '/sign-in'
    | '/sign-up'
    | '/team-management'
    | '/api/catalog'
    | '/api/certifications'
    | '/api/compliance'
    | '/api/dashboard'
    | '/api/export'
    | '/api/notification-settings'
    | '/api/notifications'
    | '/api/team-members'
    | '/api/team-requirements'
    | '/api/teams'
    | '/api/users'
    | '/user-profile/$'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  CertificationManagementRoute: typeof CertificationManagementRoute
  ComplianceAuditRoute: typeof ComplianceAuditRoute
  DbHealthRoute: typeof DbHealthRoute
  HealthRoute: typeof HealthRoute
  MetricsRoute: typeof MetricsRoute
  NotificationsRoute: typeof NotificationsRoute
  ReadyRoute: typeof ReadyRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TeamManagementRoute: typeof TeamManagementRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiCertificationsRoute: typeof ApiCertificationsRoute
  ApiComplianceRoute: typeof ApiComplianceRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiNotificationSettingsRoute: typeof ApiNotificationSettingsRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiTeamMembersRoute: typeof ApiTeamMembersRoute
  ApiTeamRequirementsRoute: typeof ApiTeamRequirementsRoute
  ApiTeamsRoute: typeof ApiTeamsRoute
  ApiUsersRoute: typeof ApiUsersRoute
  UserProfileSplatRoute: typeof UserProfileSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team-management': {
      id: '/team-management'
      path: '/team-management'
      fullPath: '/team-management'
      preLoaderRoute: typeof TeamManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-health': {
      id: '/db-health'
      path: '/db-health'
      fullPath: '/db-health'
      preLoaderRoute: typeof DbHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-audit': {
      id: '/compliance-audit'
      path: '/compliance-audit'
      fullPath: '/compliance-audit'
      preLoaderRoute: typeof ComplianceAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification-management': {
      id: '/certification-management'
      path: '/certification-management'
      fullPath: '/certification-management'
      preLoaderRoute: typeof CertificationManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-profile/$': {
      id: '/user-profile/$'
      path: '/user-profile/$'
      fullPath: '/user-profile/$'
      preLoaderRoute: typeof UserProfileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams': {
      id: '/api/teams'
      path: '/api/teams'
      fullPath: '/api/teams'
      preLoaderRoute: typeof ApiTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team-requirements': {
      id: '/api/team-requirements'
      path: '/api/team-requirements'
      fullPath: '/api/team-requirements'
      preLoaderRoute: typeof ApiTeamRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team-members': {
      id: '/api/team-members'
      path: '/api/team-members'
      fullPath: '/api/team-members'
      preLoaderRoute: typeof ApiTeamMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notification-settings': {
      id: '/api/notification-settings'
      path: '/api/notification-settings'
      fullPath: '/api/notification-settings'
      preLoaderRoute: typeof ApiNotificationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compliance': {
      id: '/api/compliance'
      path: '/api/compliance'
      fullPath: '/api/compliance'
      preLoaderRoute: typeof ApiComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certifications': {
      id: '/api/certifications'
      path: '/api/certifications'
      fullPath: '/api/certifications'
      preLoaderRoute: typeof ApiCertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  CertificationManagementRoute: CertificationManagementRoute,
  ComplianceAuditRoute: ComplianceAuditRoute,
  DbHealthRoute: DbHealthRoute,
  HealthRoute: HealthRoute,
  MetricsRoute: MetricsRoute,
  NotificationsRoute: NotificationsRoute,
  ReadyRoute: ReadyRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TeamManagementRoute: TeamManagementRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiCertificationsRoute: ApiCertificationsRoute,
  ApiComplianceRoute: ApiComplianceRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiExportRoute: ApiExportRoute,
  ApiNotificationSettingsRoute: ApiNotificationSettingsRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiTeamMembersRoute: ApiTeamMembersRoute,
  ApiTeamRequirementsRoute: ApiTeamRequirementsRoute,
  ApiTeamsRoute: ApiTeamsRoute,
  ApiUsersRoute: ApiUsersRoute,
  UserProfileSplatRoute: UserProfileSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
