import type { ComplianceReport, ComplianceReportDateRange } from '@/../product/sections/compliance-and-audit/types'
import { FileText, Download, Clock, CheckCircle2, Loader2, AlertTriangle, Plus } from 'lucide-react'
import { format } from 'date-fns'

interface ReportsSectionProps {
  reports: ComplianceReport[]
  onGenerateReport?: (reportType: 'audit-trail-export' | 'certification-status' | 'compliance-summary', dateRange?: ComplianceReportDateRange) => void
  onDownloadReport?: (reportId: string) => void
  onExportAuditTrail?: (dateRange: ComplianceReportDateRange, format: 'pdf' | 'csv') => void
}

export function ReportsSection({ reports, onGenerateReport, onDownloadReport }: ReportsSectionProps) {
  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'completed': return <CheckCircle2 className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
      case 'generating': return <Loader2 className="w-4 h-4 text-blue-600 dark:text-blue-400 animate-spin" />
      case 'pending': return <Clock className="w-4 h-4 text-amber-600 dark:text-amber-400" />
      case 'failed': return <AlertTriangle className="w-4 h-4 text-rose-600 dark:text-rose-400" />
      default: return <FileText className="w-4 h-4" />
    }
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed': return 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300'
      case 'generating': return 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300'
      case 'pending': return 'bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300'
      case 'failed': return 'bg-rose-100 dark:bg-rose-900/30 text-rose-700 dark:text-rose-300'
      default: return 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300'
    }
  }

  const getTypeLabel = (type: string) => {
    switch (type) {
      case 'audit-trail-export': return 'Audit Trail'
      case 'certification-status': return 'Certification Status'
      case 'compliance-summary': return 'Compliance Summary'
      default: return type
    }
  }

  return (
    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6 shadow-lg">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
          <FileText className="w-6 h-6 text-blue-600 dark:text-blue-400" />
          Compliance Reports
        </h2>
        <button
          onClick={() => onGenerateReport?.('compliance-summary')}
          className="px-4 py-2 bg-blue-600 hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-600 text-white text-sm font-medium rounded-lg transition-colors flex items-center gap-2"
        >
          <Plus className="w-4 h-4" />
          Generate Report
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {reports.map(report => (
          <div
            key={report.id}
            className="border border-slate-200 dark:border-slate-700 rounded-lg p-5 hover:border-blue-300 dark:hover:border-blue-700 transition-colors"
          >
            <div className="flex items-start justify-between mb-3">
              <div className="flex-1 min-w-0">
                <div className="font-semibold text-slate-900 dark:text-slate-100 mb-1 line-clamp-1">
                  {report.title}
                </div>
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-xs px-2 py-0.5 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 rounded font-medium">
                    {getTypeLabel(report.type)}
                  </span>
                  <span className={`text-xs px-2 py-0.5 rounded font-medium flex items-center gap-1 ${getStatusColor(report.status)}`}>
                    {getStatusIcon(report.status)}
                    {report.status}
                  </span>
                </div>
              </div>
            </div>

            <div className="text-xs text-slate-600 dark:text-slate-400 space-y-1 mb-4">
              <div>Generated by {report.generatedBy.name}</div>
              {report.generatedDate && (
                <div>{format(new Date(report.generatedDate), 'MMM d, yyyy')}</div>
              )}
              {report.dateRange && (
                <div>
                  {format(new Date(report.dateRange.start), 'MMM d')} - {format(new Date(report.dateRange.end), 'MMM d, yyyy')}
                </div>
              )}
              {report.fileSize && (
                <div className="text-slate-500 dark:text-slate-500">{report.fileSize}</div>
              )}
            </div>

            {report.status === 'completed' && report.downloadUrl && (
              <button
                onClick={() => onDownloadReport?.(report.id)}
                className="w-full px-4 py-2 bg-blue-600 hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-600 text-white text-sm font-medium rounded-lg transition-colors flex items-center justify-center gap-2"
              >
                <Download className="w-4 h-4" />
                Download
              </button>
            )}

            {report.status === 'generating' && (
              <div className="w-full px-4 py-2 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 text-sm font-medium rounded-lg flex items-center justify-center gap-2">
                <Loader2 className="w-4 h-4 animate-spin" />
                Generating...
              </div>
            )}

            {report.status === 'failed' && (
              <div className="w-full px-4 py-2 bg-rose-100 dark:bg-rose-900/30 text-rose-700 dark:text-rose-300 text-sm font-medium rounded-lg flex items-center justify-center gap-2">
                <AlertTriangle className="w-4 h-4" />
                Generation Failed
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}
